In [29]:
import pandas as pd

data = pd.read_csv("results.csv")
data.head()

,config,type,n_obs,n_simulations,mcar,mar,mnar,outliers,DDC,m,R,k,(intercept),X1,X2,X3
0,1,MI,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,0.001482,0.047397,-0.076605,0.061463
1,1,Boot,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,0.000499,0.040587,-0.077492,0.051557
2,1,MI DDC,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,0.001482,0.047397,-0.076605,0.061463
3,1,Boot DDC,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,-0.001549,0.041594,-0.078299,0.048349
4,1,MI,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,-0.036817,0.046668,0.094104,-0.073508

In [30]:
#square errrors
data[["(intercept)","X1","X2","X3"]] = data[["(intercept)","X1","X2","X3"]]**2
data.head()

,config,type,n_obs,n_simulations,mcar,mar,mnar,outliers,DDC,m,R,k,(intercept),X1,X2,X3
0,1,MI,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,2.197214e-06,0.002246,0.005868,0.003778
1,1,Boot,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,2.487648e-07,0.001647,0.006005,0.002658
2,1,MI DDC,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,2.197214e-06,0.002246,0.005868,0.003778
3,1,Boot DDC,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,2.397986e-06,0.001730,0.006131,0.002338
4,1,MI,200,100,0.1,0.0,0.0,0.2,True,10,1000,5,1.355502e-03,0.002178,0.008856,0.005403

In [31]:
#MSE

table = data.groupby(["config","type"]).mean().drop(columns=["n_obs","n_simulations","DDC","m","R","k"])
table[["mcar", "mar", "mnar", "outliers"]] = table[["mcar", "mar", "mnar", "outliers"]]*100
table[["mcar", "mar", "mnar", "outliers"]] = table[["mcar", "mar", "mnar", "outliers"]]
table[["(intercept)","X1","X2","X3"]] = table[["(intercept)","X1","X2","X3"]].round(3)
display(table.stack())
print(table.to_latex())

                 mcar   mar  mnar  outliers  (intercept)     X1     X2     X3
config type
1      Boot      10.0   0.0   0.0      20.0        0.004  0.004  0.005  0.004
       Boot DDC  10.0   0.0   0.0      20.0        0.004  0.005  0.005  0.004
       MI        10.0   0.0   0.0      20.0        0.004  0.004  0.005  0.004
       MI DDC    10.0   0.0   0.0      20.0        0.004  0.005  0.005  0.004
2      Boot       0.0  10.0   0.0      20.0        0.005  0.006  0.005  0.005
       Boot DDC   0.0  10.0   0.0      20.0        0.005  0.006  0.005  0.005
       MI         0.0  10.0   0.0      20.0        0.005  0.006  0.005  0.005
       MI DDC     0.0  10.0   0.0      20.0        0.006  0.006  0.005  0.005
3      Boot       0.0   0.0  10.0      20.0        0.004  0.005  0.003  0.005
       Boot DDC   0.0   0.0  10.0      20.0        0.004  0.005  0.003  0.005
       MI         0.0   0.0  10.0      20.0        0.004  0.005  0.003  0.005
       MI DDC     0.0   0.0  10.0      20.0        0.004  0.005  0.003  0.005
4      Boot      40.0   0.0   0.0      20.0        0.005  0.005  0.005  0.005
       Boot DDC  40.0   0.0   0.0      20.0        0.005  0.005  0.005  0.005
       MI        40.0   0.0   0.0      20.0        0.005  0.005  0.005  0.005
       MI DDC    40.0   0.0   0.0      20.0        0.005  0.005  0.005  0.005
5      Boot       0.0  40.0   0.0      20.0        0.006  0.006  0.005  0.006
       Boot DDC   0.0  40.0   0.0      20.0        0.006  0.006  0.005  0.006
       MI         0.0  40.0   0.0      20.0        0.006  0.006  0.005  0.006
       MI DDC     0.0  40.0   0.0      20.0        0.006  0.006  0.005  0.006
6      Boot       0.0   0.0  40.0      20.0        0.006  0.006  0.006  0.007
       Boot DDC   0.0   0.0  40.0      20.0        0.006  0.006  0.006  0.007
       MI         0.0   0.0  40.0      20.0        0.006  0.006  0.006  0.007
       MI DDC     0.0   0.0  40.0      20.0        0.006  0.006  0.006  0.007
7      Boot      10.0   0.0   0.0       0.0        0.004  0.005  0.005  0.004
       MI        10.0   0.0   0.0       0.0        0.005  0.005  0.005  0.004
8      Boot       0.0  10.0   0.0       0.0        0.006  0.007  0.006  0.007
       MI         0.0  10.0   0.0       0.0        0.006  0.007  0.006  0.007
9      Boot       0.0   0.0  10.0       0.0        0.004  0.006  0.005  0.007
       MI         0.0   0.0  10.0       0.0        0.004  0.006  0.005  0.007
10     Boot      40.0   0.0   0.0       0.0        0.006  0.005  0.007  0.005
       MI        40.0   0.0   0.0       0.0        0.006  0.006  0.007  0.005
11     Boot       0.0  40.0   0.0       0.0        0.007  0.005  0.005  0.006
       MI         0.0  40.0   0.0       0.0        0.006  0.006  0.005  0.006
12     Boot       0.0   0.0  40.0       0.0        0.005  0.007  0.006  0.005
       MI         0.0   0.0  40.0       0.0        0.005  0.007  0.006  0.005
13     Base       0.0   0.0   0.0       0.0        0.005  0.006  0.005  0.006

\begin{tabular}{llrrrrrrrr}
\toprule
   &      &  mcar &   mar &  mnar &  outliers &  (intercept) &     X1 &     X2 &     X3 \\
config & type &       &       &       &           &              &        &        &        \\
\midrule
1  & Boot &  10.0 &   0.0 &   0.0 &      20.0 &        0.004 &  0.004 &  0.005 &  0.004 \\
   & Boot DDC &  10.0 &   0.0 &   0.0 &      20.0 &        0.004 &  0.005 &  0.005 &  0.004 \\
   & MI &  10.0 &   0.0 &   0.0 &      20.0 &        0.004 &  0.004 &  0.005 &  0.004 \\
   & MI DDC &  10.0 &   0.0 &   0.0 &      20.0 &        0.004 &  0.005 &  0.005 &  0.004 \\
2  & Boot &   0.0 &  10.0 &   0.0 &      20.0 &        0.005 &  0.006 &  0.005 &  0.005 \\
   & Boot DDC &   0.0 &  10.0 &   0.0 &      20.0 &        0.005 &  0.006 &  0.005 &  0.005 \\
   & MI &   0.0 &  10.0 &   0.0 &      20.0 &        0.005 &  0.006 &  0.005 &  0.005 \\
   & MI DDC &   0.0 &  10.0 &   0.0 &      20.0 &        0.006 &  0.006 &  0.005 &  0.005 \\
3  & Boot &   0.0 &   0.0 &  10.0 &      20.0 &        0.004 &  0.005 &  0.003 &  0.005 \\
   & Boot DDC &   0.0 &   0.0 &  10.0 &      20.0 &        0.004 &  0.005 &  0.003 &  0.005 \\
   & MI &   0.0 &   0.0 &  10.0 &      20.0 &        0.004 &  0.005 &  0.003 &  0.005 \\
   & MI DDC &   0.0 &   0.0 &  10.0 &      20.0 &        0.004 &  0.005 &  0.003 &  0.005 \\
4  & Boot &  40.0 &   0.0 &   0.0 &      20.0 &        0.005 &  0.005 &  0.005 &  0.005 \\
   & Boot DDC &  40.0 &   0.0 &   0.0 &      20.0 &        0.005 &  0.005 &  0.005 &  0.005 \\
   & MI &  40.0 &   0.0 &   0.0 &      20.0 &        0.005 &  0.005 &  0.005 &  0.005 \\
   & MI DDC &  40.0 &   0.0 &   0.0 &      20.0 &        0.005 &  0.005 &  0.005 &  0.005 \\
5  & Boot &   0.0 &  40.0 &   0.0 &      20.0 &        0.006 &  0.006 &  0.005 &  0.006 \\
   & Boot DDC &   0.0 &  40.0 &   0.0 &      20.0 &        0.006 &  0.006 &  0.005 &  0.006 \\
   & MI &   0.0 &  40.0 &   0.0 &      20.0 &        0.006 &  0.006 &  0.005 &  0.006 \\
   & MI DDC &   0.0 &  40.0 &   0.0 &      20.0 &        0.006 &  0.006 &  0.005 &  0.006 \\
6  & Boot &   0.0 &   0.0 &  40.0 &      20.0 &        0.006 &  0.006 &  0.006 &  0.007 \\
   & Boot DDC &   0.0 &   0.0 &  40.0 &      20.0 &        0.006 &  0.006 &  0.006 &  0.007 \\
   & MI &   0.0 &   0.0 &  40.0 &      20.0 &        0.006 &  0.006 &  0.006 &  0.007 \\
   & MI DDC &   0.0 &   0.0 &  40.0 &      20.0 &        0.006 &  0.006 &  0.006 &  0.007 \\
7  & Boot &  10.0 &   0.0 &   0.0 &       0.0 &        0.004 &  0.005 &  0.005 &  0.004 \\
   & MI &  10.0 &   0.0 &   0.0 &       0.0 &        0.005 &  0.005 &  0.005 &  0.004 \\
8  & Boot &   0.0 &  10.0 &   0.0 &       0.0 &        0.006 &  0.007 &  0.006 &  0.007 \\
   & MI &   0.0 &  10.0 &   0.0 &       0.0 &        0.006 &  0.007 &  0.006 &  0.007 \\
9  & Boot &   0.0 &   0.0 &  10.0 &       0.0 &        0.004 &  0.006 &  0.005 &  0.007 \\
   & MI &   0.0 &   0.0 &  10.0 &       0.0 &        0.004 &  0.006 &  0.005 &  0.007 \\
10 & Boot &  40.0 &   0.0 &   0.0 &       0.0 &        0.006 &  0.005 &  0.007 &  0.005 \\
   & MI &  40.0 &   0.0 &   0.0 &       0.0 &        0.006 &  0.006 &  0.007 &  0.005 \\
11 & Boot &   0.0 &  40.0 &   0.0 &       0.0 &        0.007 &  0.005 &  0.005 &  0.006 \\
   & MI &   0.0 &  40.0 &   0.0 &       0.0 &        0.006 &  0.006 &  0.005 &  0.006 \\
12 & Boot &   0.0 &   0.0 &  40.0 &       0.0 &        0.005 &  0.007 &  0.006 &  0.005 \\
   & MI &   0.0 &   0.0 &  40.0 &       0.0 &        0.005 &  0.007 &  0.006 &  0.005 \\
13 & Base &   0.0 &   0.0 &   0.0 &       0.0 &        0.005 &  0.006 &  0.005 &  0.006 \\
\bottomrule
\end{tabular}